name: Run Python Code

on:
  schedule:
    - cron: '10 21 * * *'  # UTC 21:10 (한국 시간 06:10)
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'
          architecture: 'x64'
          cache: 'pip'
          
      - name: Verify Python version
        run: |
          which python
          python --version
          pip --version
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas requests lxml html5lib
          
      - name: Run Python script
        run: |
          python KR_SISE_SANG.py
        continue-on-error: true
