name: Run Python Code
on:
  schedule:
    - cron: '10 21 * * *'
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Remove Python 3.13
        run: |
          sudo rm -rf /opt/hostedtoolcache/Python/3.13*
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'
          architecture: 'x64'
          cache: 'pip'
          
      - name: Verify Python version
        run: |
          which python
          python --version
          pip --version
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas requests lxml html5lib

      - name: Create directories
        run: |
          mkdir -p sise_csv
          
      - name: Run Python script
        run: |
          python KR_SISE_SANG.py
