name: Run Python Code
on:
  schedule:
    - cron: '10 21 * * *'  # 매일 21:10 UTC에 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests lxml html5lib

      - name: Create directories
        run: |
          mkdir -p sise_csv
          
      - name: Run Python script
        run: |
          python KR_SISE_SANG.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}  # LINE 알림을 위한 토큰
